### ISSUE TITLE
Not able to run the project

### ISSUE THREAD

**Issue by Lubna842** [digital-asset/ex-java-bindings#10]
Im getting following error while running the project using "mvn exec:" command.

Unknown lifecycle phase ".mainClass=examples.pingpong.reactive.PingPongReactiveMain". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, 
generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException

**Comment by Lubna842** [comment]
resolved

**Comment by cocreature** [comment]
See https://discuss.daml.com/t/error-on-running-pingpong-example/1707 for the resolution.
