### ISSUE TITLE
About and README mention *three* examples, but there are only two

### ISSUE THREAD

**Issue by wallacekelly-da** [digital-asset/ex-java-bindings#18]
The About and README mention *three* examples, but there are only two examples. (The third example was dropped [here](71be5b242d00309cd7d9018f3540e5c4dcf98f7f).)

![image](https://user-images.githubusercontent.com/116685059/213276707-0c204bac-ba5a-4315-bd32-0cfb32dd8309.png)

I will create a PR to update the README.rst, but I do not have permissions to [edit the About](https://stackoverflow.com/a/71247647/167920).

**Comment by dasormeter** [comment]
think this is outdated
